libhpdftbl: /Users/ljp/Devel/hpdf_table/src/hpdftbl.h File Reference
hpdftbl.h File Reference
Necessary header file for HPDF table usage.
Data Structures
struct text_style
Specification of a text style.
struct grid_style
Specification for table grid lines.
struct hpdftbl_cell
Specification of individual cells in the table.
struct hpdftbl
Core table handle.
struct hpdftbl_cell_spec
Used in data driven table creation.
struct hpdftbl_spec
Used in data driven table creation.
struct hpdftbl_theme
Define a set of styles into a table theme.
Macros
#define HPDF_FF_TIMES "Times-Roman"
#define HPDF_FF_TIMES_ITALIC "Times-Italic"
#define HPDF_FF_TIMES_BOLD "Times-Bold"
#define HPDF_FF_TIMES_BOLDITALIC "Times-BoldItalic"
#define HPDF_FF_HELVETICA "Helvetica"
#define HPDF_FF_HELVETICA_ITALIC "Helvetica-Oblique"
#define HPDF_FF_HELVETICA_BOLD "Helvetica-Bold"
#define HPDF_FF_HELVETICA_BOLDITALIC "Helvetica-BoldOblique"
#define HPDF_FF_COURIER "Courier"
#define HPDF_FF_COURIER_BOLD "Courier-Bold"
#define HPDF_FF_COURIER_IALIC "Courier-Oblique"
#define HPDF_FF_COURIER_BOLDITALIC "Courier-BoldOblique"
#define HPDF_COLOR_DARK_RED (HPDF_RGBColor) { 0.6f, 0.0f, 0.0f }
#define HPDF_COLOR_RED (HPDF_RGBColor) { 1.0f, 0.0f, 0.0f }
#define HPDF_COLOR_LIGHT_GREEN (HPDF_RGBColor) { 0.9f, 1.0f, 0.9f }
#define HPDF_COLOR_GREEN (HPDF_RGBColor) { 0.4f, 0.9f, 0.4f }
#define HPDF_COLOR_DARK_GREEN (HPDF_RGBColor) { 0.05f, 0.37f, 0.02f }
#define HPDF_COLOR_DARK_GRAY (HPDF_RGBColor) { 0.2f, 0.2f, 0.2f }
#define HPDF_COLOR_LIGHT_GRAY (HPDF_RGBColor) { 0.9f, 0.9f, 0.9f }
#define HPDF_COLOR_GRAY (HPDF_RGBColor) { 0.5f, 0.5f, 0.5f }
#define HPDF_COLOR_SILVER (HPDF_RGBColor) { 0.75f, 0.75f, 0.75f }
#define HPDF_COLOR_LIGHT_BLUE (HPDF_RGBColor) { 1.0f, 1.0f, 0.9f }
#define HPDF_COLOR_BLUE (HPDF_RGBColor) { 0.0f, 0.0f, 1.0f }
#define HPDF_COLOR_DARK_BLUE (HPDF_RGBColor) { 0.0f, 0.0f, 0.6f }
#define HPDF_COLOR_WHITE (HPDF_RGBColor) { 1.0f, 1.0f, 1.0f }
#define HPDF_COLOR_BLACK (HPDF_RGBColor) { 0.0f, 0.0f, 0.0f }
#define HPDFTBL_DEFAULT_TARGET_ENCODING "ISO8859-4"
#define HPDFTBL_DEFAULT_SOURCE_ENCODING "UTF-8"
#define HPDFTBL_TEXT_HALIGN_LEFT 0
#define HPDFTBL_TEXT_HALIGN_CENTER 1
#define HPDFTBL_TEXT_HALIGN_RIGHT 2
#define A4PAGE_HEIGHT_CM 29.7
#define A4PAGE_WIDTH_CM 21.0
#define A3PAGE_HEIGHT_CM 42.0
#define A3PAGE_WIDTH_CM 29.7
#define LETTERRPAGE_HEIGHT_CM 27.9
#define LETTERRPAGE_WIDTH_CM 21.6
#define LEGALPAGE_HEIGHT_CM 35.6
#define LEGALPAGE_WIDTH_CM 21.6
#define HPDFTBL_END_CELLSPECS {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define HPDF_COLOR_FROMRGB(r, g, b) (HPDF_RGBColor){(r)/255.0,(g)/255.0,(b)/255.0}
#define MIN_CALCULATED_PERCENT_CELL_WIDTH 2.0
#define hpdftbl_cm2dpi(c) (((HPDF_REAL)(c))/2.54*72)
Convert cm to dots using the default resolution (72 DPI)
Typedefs
typedef enum hpdftbl_text_align hpdftbl_text_align_t
Enumeration for horizontal text alignment.
typedef struct text_style hpdf_text_style_t
Specification of a text style.
typedef char *(* hpdftbl_content_callback_t) (void *, size_t, size_t)
Type specification for the table content callback.
typedef void(* hpdftbl_canvas_callback_t) (HPDF_Doc, HPDF_Page, void *, size_t, size_t, HPDF_REAL, HPDF_REAL, HPDF_REAL, HPDF_REAL)
Type specification for the table canvas callback.
typedef _Bool(* hpdftbl_content_style_callback_t) (void *, size_t, size_t, char *content, hpdf_text_style_t *)
Type specification for the content style.
typedef enum hpdftbl_dashstyle hpdftbl_line_dashstyle_t
Possible line dash styles for grid lines.
typedef struct grid_style hpdftbl_grid_style_t
Specification for table grid lines.
typedef struct hpdftbl_cell hpdftbl_cell_t
Type definition for the cell structure.
typedef struct hpdftbl * hpdftbl_t
Table handle is a pointer to the hpdftbl structure.
typedef void(* hpdftbl_callback_t) (hpdftbl_t)
Callback type for optional post processing when constructing table from a data array.
typedef struct hpdftbl_cell_spec hpdftbl_cell_spec_t
Used in data driven table creation.
typedef struct hpdftbl_spec hpdftbl_spec_t
Used in data driven table creation.
typedef struct hpdftbl_theme hpdftbl_theme_t
Define a set of styles into a table theme.
typedef void(* hpdftbl_error_handler_t) (hpdftbl_t, int, int, int)
TYpe for error handler function.
Enumerations
enum hpdftbl_text_align { LEFT = 0 , CENTER = 1 , RIGHT = 2 }
Enumeration for horizontal text alignment.
enum hpdftbl_dashstyle {
LINE_SOLID = 0 , LINE_DOT1 = 1 , LINE_DOT2 = 2 , LINE_DOT3 = 3 ,
LINE_DASH1 = 4 , LINE_DASH2 = 5 , LINE_DASH3 = 6 , LINE_DASHDOT = 7
}
Possible line dash styles for grid lines.
Functions
hpdftbl_t hpdftbl_create (size_t rows, size_t cols)
Create a new table with no title.
hpdftbl_t hpdftbl_create_title (size_t rows, size_t cols, char *title)
Create a new table with title top row.
int hpdftbl_stroke (HPDF_Doc pdf, HPDF_Page page, hpdftbl_t t, HPDF_REAL xpos, HPDF_REAL ypos, HPDF_REAL width, HPDF_REAL height)
Stroke the table.
int hpdftbl_stroke_from_data (HPDF_Doc pdf_doc, HPDF_Page pdf_page, hpdftbl_spec_t *tbl_spec, hpdftbl_theme_t *theme)
Construct the table from a array specification.
int hpdftbl_destroy (hpdftbl_t t)
Destroy a table and free all memory.
int hpdftbl_get_last_auto_height (HPDF_REAL *height)
Get the height calculated for the last constructed table.
void hpdftbl_set_anchor_top_left (_Bool anchor)
Switch stroking anchor point.
_Bool hpdftbl_get_anchor_top_left (void)
Get stroking anchor point.
hpdftbl_error_handler_t hpdftbl_set_errhandler (hpdftbl_error_handler_t)
Specify errhandler for the table routines.
const char * hpdftbl_get_errstr (int err)
Translate a table error code to a human readable string.
const char * hpdftbl_hpdf_get_errstr (HPDF_STATUS err_code)
Function to return a human readable error string for an error code from Core HPDF library.
int hpdftbl_get_last_errcode (const char **errstr, int *row, int *col)
Return last error code.
void hpdftbl_default_table_error_handler (hpdftbl_t t, int r, int c, int err)
A simple default table error handler callback that outputs the error to stderr in human readable format and quits the process.
int hpdftbl_apply_theme (hpdftbl_t t, hpdftbl_theme_t *theme)
Apply a specified theme to a table.
hpdftbl_theme_t * hpdftbl_get_default_theme (void)
Return the default theme.
int hpdftbl_destroy_theme (hpdftbl_theme_t *theme)
Destroy existing theme structure and free memory.
int hpdftbl_set_colwidth_percent (hpdftbl_t t, size_t c, float w)
Set column width as percentage of overall table width.
int hpdftbl_clear_spanning (hpdftbl_t t)
Clear all cell spanning.
int hpdftbl_set_cellspan (hpdftbl_t t, size_t r, size_t c, size_t rowspan, size_t colspan)
Set cell spanning.
int hpdftbl_use_labels (hpdftbl_t t, _Bool use)
int hpdftbl_use_labelgrid (hpdftbl_t t, _Bool use)
int hpdftbl_set_background (hpdftbl_t t, HPDF_RGBColor background)
Set table background color.
int hpdftbl_set_inner_tgrid_style (hpdftbl_t t, HPDF_REAL width, HPDF_RGBColor color, hpdftbl_line_dashstyle_t dashstyle)
Set inner horizontal top border grid style. This would be the gridline just below the header row.
int hpdftbl_set_inner_vgrid_style (hpdftbl_t t, HPDF_REAL width, HPDF_RGBColor color, hpdftbl_line_dashstyle_t dashstyle)
Set inner vertical border grid style.
int hpdftbl_set_inner_hgrid_style (hpdftbl_t t, HPDF_REAL width, HPDF_RGBColor color, hpdftbl_line_dashstyle_t dashstyle)
Set inner horizontal border grid style.
int hpdftbl_set_inner_grid_style (hpdftbl_t t, HPDF_REAL width, HPDF_RGBColor color, hpdftbl_line_dashstyle_t dashstyle)
Set inner border grid style.
int hpdftbl_set_outer_grid_style (hpdftbl_t t, HPDF_REAL width, HPDF_RGBColor color, hpdftbl_line_dashstyle_t dashstyle)
Set outer border grid style.
int hpdftbl_set_header_style (hpdftbl_t t, char *font, HPDF_REAL fsize, HPDF_RGBColor color, HPDF_RGBColor background)
Specify style for table header row.
int hpdftbl_set_header_halign (hpdftbl_t t, hpdftbl_text_align_t align)
Set table header text align.
int hpdftbl_use_header (hpdftbl_t t, _Bool use)
int hpdftbl_set_label_style (hpdftbl_t t, char *font, HPDF_REAL fsize, HPDF_RGBColor color, HPDF_RGBColor background)
Set the font style for labels.
int hpdftbl_set_row_content_style (hpdftbl_t t, size_t r, char *font, HPDF_REAL fsize, HPDF_RGBColor color, HPDF_RGBColor background)
Set the font style for an entire row of cells.
int hpdftbl_set_col_content_style (hpdftbl_t t, size_t c, char *font, HPDF_REAL fsize, HPDF_RGBColor color, HPDF_RGBColor background)
Set the font style for an entre column of cells.
int hpdftbl_set_content_style (hpdftbl_t t, char *font, HPDF_REAL fsize, HPDF_RGBColor color, HPDF_RGBColor background)
Set font style for text content.
int hpdftbl_set_cell_content_style (hpdftbl_t t, size_t r, size_t c, char *font, HPDF_REAL fsize, HPDF_RGBColor color, HPDF_RGBColor background)
Set the font style for content of specified cell.
int hpdftbl_set_title_style (hpdftbl_t t, char *font, HPDF_REAL fsize, HPDF_RGBColor color, HPDF_RGBColor background)
Set the table title style.
int hpdftbl_set_cell (hpdftbl_t t, int r, int c, char *label, char *content)
Set content for specific cell.
int hpdftbl_set_tag (hpdftbl_t t, void *tag)
Set an optional tag for the table.
int hpdftbl_set_title (hpdftbl_t t, char *title)
Set table title.
int hpdftbl_set_title_halign (hpdftbl_t t, hpdftbl_text_align_t align)
Set horizontal alignment for table title.
int hpdftbl_set_labels (hpdftbl_t t, char **labels)
Set the text for the cell labels.
int hpdftbl_set_content (hpdftbl_t t, char **content)
Set the content for the table.
int hpdftbl_set_content_cb (hpdftbl_t t, hpdftbl_content_callback_t cb)
Set table content callback.
int hpdftbl_set_cell_content_cb (hpdftbl_t t, size_t r, size_t c, hpdftbl_content_callback_t cb)
Set cell content callback.
int hpdftbl_set_cell_content_style_cb (hpdftbl_t t, size_t r, size_t c, hpdftbl_content_style_callback_t cb)
Set cell specific callback to specify cell content style.
int hpdftbl_set_content_style_cb (hpdftbl_t t, hpdftbl_content_style_callback_t cb)
Set callback to specify cell content style.
int hpdftbl_set_label_cb (hpdftbl_t t, hpdftbl_content_callback_t cb)
Set table label callback.
int hpdftbl_set_cell_label_cb (hpdftbl_t t, size_t r, size_t c, hpdftbl_content_callback_t cb)
Set cell label callback.
int hpdftbl_set_canvas_cb (hpdftbl_t t, hpdftbl_canvas_callback_t cb)
Set cell canvas callback.
int hpdftbl_set_cell_canvas_cb (hpdftbl_t t, size_t r, size_t c, hpdftbl_canvas_callback_t cb)
Set cell canvas callback.
void hpdftbl_set_text_encoding (char *target, char *source)
Determine text source encoding.
int hpdftbl_encoding_text_out (HPDF_Page page, HPDF_REAL xpos, HPDF_REAL ypos, char *text)
Strke text with current encoding.
void HPDF_RoundedCornerRectangle (HPDF_Page page, HPDF_REAL xpos, HPDF_REAL ypos, HPDF_REAL width, HPDF_REAL height, HPDF_REAL rad)
Draw rectangle with rounded corner.
void hpdftbl_stroke_grid (HPDF_Doc pdf, HPDF_Page page)
void hpdftbl_table_widget_letter_buttons (HPDF_Doc doc, HPDF_Page page, HPDF_REAL xpos, HPDF_REAL ypos, HPDF_REAL width, HPDF_REAL height, HPDF_RGBColor on_color, HPDF_RGBColor off_color, HPDF_RGBColor on_background, HPDF_RGBColor off_background, HPDF_REAL fsize, const char *letters, _Bool *state)
Display an array of letters as a table where each letter is its own "mini" cell
and sorrounded by a frame. Each boxed letter can be in an "on" state or "off" state which is illustrated with different font and fac colors.
void hpdftbl_widget_slide_button (HPDF_Doc doc, HPDF_Page page, HPDF_REAL xpos, HPDF_REAL ypos, HPDF_REAL width, HPDF_REAL height, _Bool state)
Table widget that draws a sliding on/off switch. Meant to be used in a canvas callback to display a boolean value.
void hpdftbl_widget_hbar (HPDF_Doc doc, HPDF_Page page, HPDF_REAL xpos, HPDF_REAL ypos, HPDF_REAL width, HPDF_REAL height, HPDF_RGBColor color, float val, _Bool hide_val)
Draw a horizontal partially filled bar to indicate an analog (percentage) value.
void hpdftbl_widget_segment_hbar (HPDF_Doc doc, HPDF_Page page, HPDF_REAL xpos, HPDF_REAL ypos, HPDF_REAL width, HPDF_REAL height, size_t num_segments, HPDF_RGBColor on_color, double val_percent, _Bool hide_val)
Draw a horizontal segment meter that can be used to visualize a discrete value.
void hpdftbl_widget_strength_meter (HPDF_Doc doc, HPDF_Page page, HPDF_REAL xpos, HPDF_REAL ypos, HPDF_REAL width, HPDF_REAL height, size_t num_segments, HPDF_RGBColor on_color, size_t num_on_segments)
Draw a phone strength meter.
Detailed Description
Necessary header file for HPDF table usage.
Macro Definition Documentation
A3PAGE_HEIGHT_CM
#define A3PAGE_HEIGHT_CM 42.0
A3 Height in CM
A3PAGE_WIDTH_CM
#define A3PAGE_WIDTH_CM 29.7
A3 Width in CM
A4PAGE_HEIGHT_CM
#define A4PAGE_HEIGHT_CM 29.7
A4 Height in CM
Examples
tut_ex01.c, tut_ex02.c, tut_ex02_1.c, tut_ex03.c, tut_ex04.c, tut_ex05.c, tut_ex06.c, tut_ex07.c, tut_ex08.c, tut_ex09.c, tut_ex10.c, tut_ex11.c, tut_ex12.c, tut_ex13_1.c, tut_ex13_2.c, tut_ex14.c, and tut_ex20.c.
A4PAGE_WIDTH_CM
#define A4PAGE_WIDTH_CM 21.0
A4 Width in CM
Examples
tut_ex02_1.c, tut_ex09.c, tut_ex10.c, tut_ex11.c, and tut_ex12.c.
HPDF_COLOR_DARK_RED
#define HPDF_COLOR_DARK_RED (HPDF_RGBColor) { 0.6f, 0.0f, 0.0f }
Basic color definitions
Examples
example01.c, and tut_ex14.c.
HPDF_COLOR_FROMRGB
#define HPDF_COLOR_FROMRGB (r, g, b) (HPDF_RGBColor){(r)/255.0,(g)/255.0,(b)/255.0}
Utility macro to calculate a color constant from RGB integer values [0,255]
HPDF_FF_TIMES
#define HPDF_FF_TIMES "Times-Roman"
Definition of built-in HPDF font families
Examples
tut_ex09.c.
hpdftbl_cm2dpi
#define hpdftbl_cm2dpi (c) (((HPDF_REAL)(c))/2.54*72)
Convert cm to dots using the default resolution (72 DPI)
Parameters
cm Measure in cm
Returns
HPDF_REAL Converted value in dots
Examples
tut_ex01.c, tut_ex02.c, tut_ex02_1.c, tut_ex03.c, tut_ex04.c, tut_ex05.c, tut_ex06.c, tut_ex07.c, tut_ex08.c, tut_ex09.c, tut_ex10.c, tut_ex11.c, tut_ex12.c, tut_ex13_1.c, tut_ex13_2.c, tut_ex14.c, and tut_ex20.c.
HPDFTBL_DEFAULT_TARGET_ENCODING
#define HPDFTBL_DEFAULT_TARGET_ENCODING "ISO8859-4"
Text encodings
HPDFTBL_END_CELLSPECS
#define HPDFTBL_END_CELLSPECS {0, 0, 0, 0, 0, 0, 0, 0, 0}
Sentinel to mark the end of Cell Specifications for data driven table definition
Examples
tut_ex13_2.c.
LEGALPAGE_HEIGHT_CM
#define LEGALPAGE_HEIGHT_CM 35.6
US Legal Height in CM
LEGALPAGE_WIDTH_CM
#define LEGALPAGE_WIDTH_CM 21.6
US Legal Width in CM
LETTERRPAGE_HEIGHT_CM
#define LETTERRPAGE_HEIGHT_CM 27.9
US Letter Height in CM
LETTERRPAGE_WIDTH_CM
#define LETTERRPAGE_WIDTH_CM 21.6
US Letter Width in CM
MIN_CALCULATED_PERCENT_CELL_WIDTH
#define MIN_CALCULATED_PERCENT_CELL_WIDTH 2.0
The smallest size in percent of table width allowed by automatic calculation before giving an error
Typedef Documentation
hpdf_text_style_t
typedef struct text_style hpdf_text_style_t
Specification of a text style.
This structure collects the basic properties for a text string (font, color, background, horizontal alignment)
hpdftbl_callback_t
typedef void(* hpdftbl_callback_t) (hpdftbl_t)
Callback type for optional post processing when constructing table from a data array.
Type for generic table callback used when constructing a table from data. This can be used to perform any potential table manipulation. The callback happens after the table has been fully constructed and just before it is stroked.
See also
hpdftbl_stroke_from_data()
hpdftbl_canvas_callback_t
typedef void(* hpdftbl_canvas_callback_t) (HPDF_Doc, HPDF_Page, void *, size_t, size_t, HPDF_REAL, HPDF_REAL, HPDF_REAL, HPDF_REAL)
Type specification for the table canvas callback.
A canvas callback, if specified, is called for each cell before the content is stroked. The callback will be given the bounding box for the cell (x,y,width,height) in addition to the row and column the cell has.
See also
hpdftbl_set_canvas_callback()
hpdftbl_cell_spec_t
typedef struct hpdftbl_cell_spec hpdftbl_cell_spec_t
Used in data driven table creation.
A table can be specified by creating a array of this structure together with the hpdftbl_spec_t structure. The array should have one entry for each cell in the table.
See also
hpdftbl_stroke_from_data()
hpdftbl_cell_t
typedef struct hpdftbl_cell hpdftbl_cell_t
Type definition for the cell structure.
This is an internal structure that represents an individual cell in the table.
hpdftbl_content_callback_t
typedef char *(* hpdftbl_content_callback_t) (void *, size_t, size_t)
Type specification for the table content callback.
The content callback is used to specify the textual content in a cell and is an alternative method to specifying the content to be displayed.
See also
hpdftbl_set_content_callback()
hpdftbl_content_style_callback_t
typedef _Bool(* hpdftbl_content_style_callback_t) (void *, size_t, size_t, char *content, hpdf_text_style_t *)
Type specification for the content style.
The content callback is used to specify the textual style in a cell and is an alternative method to specifying the style of content to be displayed.
See also
hpdftbl_set_content_style_callback()
hpdftbl_error_handler_t
typedef void(* hpdftbl_error_handler_t) (hpdftbl_t, int, int, int)
TYpe for error handler function.
The error handler (of set) will be called if the table library descovers an error condition
See also
hpdftbl_set_errhandler()
hpdftbl_grid_style_t
typedef struct grid_style hpdftbl_grid_style_t
Specification for table grid lines.
Contains line properties used when stroking a grid line
hpdftbl_spec_t
typedef struct hpdftbl_spec hpdftbl_spec_t
Used in data driven table creation.
This is used together with an array of cell specification hpdftbl_cell_spec_t to specify the layout of a table.
hpdftbl_t
typedef struct hpdftbl* hpdftbl_t
Table handle is a pointer to the hpdftbl structure.
This is the basic table handle used in almost all API calls. A table reference is returned when a table is created.
See also
hpdftbl_create()
hpdftbl_text_align_t
typedef enum hpdftbl_text_align hpdftbl_text_align_t
Enumeration for horizontal text alignment.
See also
hpdftbl_set_header_halign()
hpdftbl_set_title_halign()
hpdftbl_text_align
hpdftbl_theme_t
typedef struct hpdftbl_theme hpdftbl_theme_t
Define a set of styles into a table theme.
Contains all information about the styles of various elements in the table that together make up the table style
Enumeration Type Documentation
hpdftbl_dashstyle
enum hpdftbl_dashstyle
Possible line dash styles for grid lines.
Enumerator
LINE_SOLID
Solid line
LINE_DOT1
Dotted line variant 1
LINE_DOT2
Dotted line variant 2
LINE_DOT3
Dotted line variant 3
LINE_DASH1
Dashed line variant 1
LINE_DASH2
Dashed line variant 2
LINE_DASH3
Dashed line variant 3
LINE_DASHDOT
Dashed-dot line variant 1
hpdftbl_text_align
enum hpdftbl_text_align
Enumeration for horizontal text alignment.
See also
hpdftbl_set_header_halign()
hpdftbl_set_title_halign()
hpdftbl_text_align
Enumerator
LEFT
Left test alignment
CENTER
Center test alignment
RIGHT
Right test alignment
Function Documentation
HPDF_RoundedCornerRectangle()
void HPDF_RoundedCornerRectangle (HPDF_Page page, HPDF_REAL xpos, HPDF_REAL ypos, HPDF_REAL width, HPDF_REAL height, HPDF_REAL rad)
Draw rectangle with rounded corner.
Draw a rectangle with rounded corner with the current line width, color. The rectangle will not be stroked.
Parameters
page Page handle
xpos Lower left x-position of rectangle
ypos Lower left y-position of rectangle
width Width of rectangle
height Height of rectangle
rad Radius of corners
Referenced by hpdftbl_widget_slide_button().
hpdftbl_apply_theme()
int hpdftbl_apply_theme (hpdftbl_t t, hpdftbl_theme_t * theme)
Apply a specified theme to a table.
Apply a specified theme to a table. The default table can be retrieved with hpdftbl_get_default_theme()
Parameters
t Table handle
theme Theme reference
Returns
0 on success, -1 on failure
See also
hpdftbl_get_default_theme()
hpdftbl_clear_spanning()
int hpdftbl_clear_spanning (hpdftbl_t t)
Clear all cell spanning.
Reset all spanning cells to no spanning
Parameters
t Table handle
Returns
0 on success, -1 on failure
See also
hpdftbl_set_cellspan()
hpdftbl_create()
hpdftbl_t hpdftbl_create (size_t rows, size_t cols)
Create a new table with no title.
Create a new table structure. This is the basic handler needed for most other API functions.
Parameters
rows Number of rows
cols Number of columns
Returns
A handle to a table, NULL in case of OOM
hpdftbl_create_title()
hpdftbl_t hpdftbl_create_title (size_t rows, size_t cols, char * title)
Create a new table with title top row.
Create a new table structure. This is the basic handler needed for most other API functions.
Parameters
rows Number of rows
cols Number of columns
title Title of table
Returns
A handle to a table, NULL in case of OOM
Referenced by hpdftbl_create(), and hpdftbl_stroke_from_data().
hpdftbl_default_table_error_handler()
void hpdftbl_default_table_error_handler (hpdftbl_t t, int r, int c, int err)
A simple default table error handler callback that outputs the error to stderr in human readable format and quits the process.
Parameters
t Table where the error happened (can be NULL)
r Cell row
c Cell column
err The error code
hpdftbl_destroy()
int hpdftbl_destroy (hpdftbl_t t)
Destroy a table and free all memory.
Destroy a table previous created with table_create()
Parameters
t Handle to table
Returns
0 on success, -1 on failure
hpdftbl_destroy_theme()
int hpdftbl_destroy_theme (hpdftbl_theme_t * theme)
Destroy existing theme structure and free memory.
Free all memory allocated by a theme
Parameters
theme The theme to free
Returns
-1 for error , 0 for success
hpdftbl_encoding_text_out()
int hpdftbl_encoding_text_out (HPDF_Page page, HPDF_REAL xpos, HPDF_REAL ypos, char * text)
Strke text with current encoding.
Utility function to stroke text with character encoding. It is the calling routines responsibility to enclose text in a HPDF_Page_BeginText() / HPDF_Page_EndText()
Parameters
page Page handle
xpos X coordinate
ypos Y coordinate
text Text to print
Returns
-1 on error, 0 on success
hpdftbl_get_anchor_top_left()
_Bool hpdftbl_get_anchor_top_left (void)
Get stroking anchor point.
Get base point for table positioning. By default the top left is used.
See also
hpdftbl_set_anchor_top_left
Returns
TRUE if anchor is top left, FALSE otherwise
hpdftbl_get_default_theme()
hpdftbl_theme_t * hpdftbl_get_default_theme (void)
Return the default theme.
Create and return a theme corresponding to the default table theme. It is the calling functions responsibility to call hpdftbl_destroy_theme() to free the allocated memory. The default theme is a good starting point to just make minor modifications without having to define all elements.
Returns
A new theme initialized to the default settings
See also
hpdftbl_apply_theme()
hpdftbl_get_errstr()
const char * hpdftbl_get_errstr (int err)
Translate a table error code to a human readable string.
The function returns a pointer to a static string that cannot be modified. It will translate both internal table error messages as well as generic HPDF library error codes.
Parameters
err The error code to be translated
Returns
Static pointer to string for valid error code, NULL otherwise
See also
hpdftbl_hpdf_get_errstr()
Referenced by hpdftbl_default_table_error_handler(), and hpdftbl_get_last_errcode().
hpdftbl_get_last_auto_height()
int hpdftbl_get_last_auto_height (HPDF_REAL * height)
Get the height calculated for the last constructed table.
Get the last automatically calculated heigh when stroking a table. (The height will be automatically calculated if it was specified as 0)
Parameters
height Returned height
Returns
-1 on error, 0 if successful
hpdftbl_get_last_errcode()
int hpdftbl_get_last_errcode (const char ** errstr, int * row, int * col)
Return last error code.
Return last error code. if errstr is not NULL a human readable string describing the error will be copied to the string. The error code will be reset after call.
Parameters
errstr A string buffer where the error string is written to
row The row where the error was found
col The col where the error was found
Returns
The last error code
hpdftbl_hpdf_get_errstr()
const char * hpdftbl_hpdf_get_errstr (const HPDF_STATUS err_code)
Function to return a human readable error string for an error code from Core HPDF library.
The various error codes given by the HPDF library can be translated back to a string by the usage of this function. The function will return a pointer to a static string that can not be manipulated.
Parameters
err_code The error code
Returns
A pointer to an error string, NULL if the error code is invalid
See also
hpdftbl_get_errstr()
Examples
example01.c, tut_ex01.c, tut_ex02.c, tut_ex02_1.c, tut_ex03.c, tut_ex04.c, tut_ex05.c, tut_ex06.c, tut_ex07.c, tut_ex08.c, tut_ex09.c, tut_ex10.c, tut_ex11.c, tut_ex12.c, tut_ex13_1.c, tut_ex13_2.c, tut_ex14.c, and tut_ex20.c.
hpdftbl_set_anchor_top_left()
void hpdftbl_set_anchor_top_left (const _Bool anchor)
Switch stroking anchor point.
Set anchor point for table positioning. By default the top left is used as anchor. Calling this function with FALSE can set the basepoint to bottom left instead.
Parameters
anchor Set to TRUE to use top left as anchor, FALSE for bottom left
hpdftbl_set_background()
int hpdftbl_set_background (hpdftbl_t t, HPDF_RGBColor background)
Set table background color.
Set table background
Parameters
t Table handle
background Background color
Returns
0 on success, -1 on failure
hpdftbl_set_canvas_cb()
int hpdftbl_set_canvas_cb (hpdftbl_t t, hpdftbl_canvas_callback_t cb)
Set cell canvas callback.
Set cell canvas callback. This callback gets called for each cell in the table. The purpose is to allow the client to add dynamic content to the specified cell. The callback is made before the cell border and content is drawn making it possible to for example add a background color to individual cells. The callback function will receive the Table tag, the row and column, the x, y position of the lower left corner of the table and the width and height of the cell. To set the canvas callback only for a sepcific cell use the hpdftbl_set_cell_canvas_callback() function
Parameters
t Table handle
cb Callback function
Returns
-1 on failure, 0 otherwise
See also
hpdftbl_set_cell_canvas_cb()
hpdftbl_set_cell()
int hpdftbl_set_cell (hpdftbl_t t, int r, int c, char * label, char * content)
Set content for specific cell.
Set label and content for a specific cell. If the specified cell is part of another cells spanning then error is given (returns -1),
Parameters
t Table handle
r Row
c Column
label Label
content Text content
Returns
-1 on error, 0 if successful
hpdftbl_set_cell_canvas_cb()
int hpdftbl_set_cell_canvas_cb (hpdftbl_t t, size_t r, size_t c, hpdftbl_canvas_callback_t cb)
Set cell canvas callback.
Set a canvas callback for an individual cell. This will override the table canvas callback. The canvas callback is called with arguments that give the bounding box for the cell. In that way a callback function may draw arbitrary graphic in the cell. The callback is made before the cell border and content is drawn making it possible to for example add a background color to individual cells. The callback function will receive the Table tag, the row and column, the x, y position of the lower left corner of the table and the width and height of the cell.
Parameters
t Table handle
r Cell row
c Cell column
cb Callback function
Returns
-1 on failure, 0 otherwise
See also
hpdftbl_canvas_callback_t
hpdftbl_set_canvas_callback
hpdftbl_set_cell_content_cb()
int hpdftbl_set_cell_content_cb (hpdftbl_t t, size_t r, size_t c, hpdftbl_content_callback_t cb)
Set cell content callback.
Set a content callback for an individual cell. This will override the table content callback.
Parameters
t Table handle
cb Callback function
r Cell row
c Cell column
Returns
-1 on failure, 0 otherwise
See also
hpdftbl_set_content_cb()
hpdftbl_set_cell_content_style()
int hpdftbl_set_cell_content_style (hpdftbl_t t, size_t r, size_t c, char * font, HPDF_REAL fsize, HPDF_RGBColor color, HPDF_RGBColor background)
Set the font style for content of specified cell.
SSet the font style for content of specified cell. This will override the global cell content setting.
Parameters
t Table handle
r Cell row
c Cell column
font Font name
fsize Font size
color Color
background Background color
Returns
0 on success, -1 on failure
See also
hpdftbl_set_content_style()
hpdftbl_set_cell_content_style_cb()
Referenced by hpdftbl_set_col_content_style(), and hpdftbl_set_row_content_style().
hpdftbl_set_cell_content_style_cb()
int hpdftbl_set_cell_content_style_cb (hpdftbl_t t, size_t r, size_t c, hpdftbl_content_style_callback_t cb)
Set cell specific callback to specify cell content style.
Set callback to format the style for the specified cell
Parameters
t Table handle
r Cell row
c Cell column
cb Callback function
Returns
0 on success, -1 on failure
See also
hpdftbl_set_ontent_style_cb()
hpdftbl_set_cell_label_cb()
int hpdftbl_set_cell_label_cb (hpdftbl_t t, size_t r, size_t c, hpdftbl_content_callback_t cb)
Set cell label callback.
Set a label callback for an individual cell. This will override the table content callback.
Parameters
t Table handle
cb Callback function
r Cell row
c Cell column
Returns
-1 on failure, 0 otherwise
See also
hpdftbl_set_label_cb()
hpdftbl_set_cellspan()
int hpdftbl_set_cellspan (hpdftbl_t t, size_t r, size_t c, size_t rowspan, size_t colspan)
Set cell spanning.
Set row and column spanning for a cell
Parameters
t Table handle
r Row
c Column
rowspan Row span
colspan Column span
Returns
-1 on error, 0 if successful
See also
hpdftbl_clear_spanning()
hpdftbl_set_col_content_style()
int hpdftbl_set_col_content_style (hpdftbl_t t, size_t c, char * font, HPDF_REAL fsize, HPDF_RGBColor color, HPDF_RGBColor background)
Set the font style for an entre column of cells.
Set font options for the specified column of cells. This will override the global cell content setting.
Parameters
t Table handle
c Column to affect
font Font name
fsize Font size
color Color
background Background color
Returns
0 on success, -1 on failure
See also
hpdftbl_set_content_style()
hpdftbl_set_cell_content_style_cb()
hpdftbl_set_colwidth_percent()
int hpdftbl_set_colwidth_percent (hpdftbl_t t, size_t c, float w)
Set column width as percentage of overall table width.
Specify column width as percentage of total column width. Note that this will only take effect if the table has an overall width specified when stroked.
Parameters
t Table handle
c Column to set width of first column has index 0
w Width as percentage in range [0.0, 100.0]
Returns
0 on success, -1 on failure
hpdftbl_set_content()
int hpdftbl_set_content (hpdftbl_t t, char ** content)
Set the content for the table.
Set content for all cells. It is the calling functions responsibility that the content array is big enough to cover the entire table. The string array corresponds to a flattened 2-d array and the label for cell (r,c) is calculated as (r * num_cols + c) where num_cols is the number of columns in the table. It is allowed to specify NULL as placeholder for empty labels. The actual text in the table will be allocated with strdup() so it is safe to free the memory for the labels after the call to this function. Please note that even if the table contains spanning cells the content data must include empty data for covered cells. For a N x M table the data must have (N*M) entries. Another way to specify the content is to use the callback mechanism. By setting up a content callback function that returns the content for a cell
Parameters
t Table handle
content A one dimensional string array of content string
Returns
-1 on error, 0 if successful
See also
hpdftbl_set_content_callback()
hpdftbl_set_cell_content_callback()
hpdftbl_set_content_cb()
int hpdftbl_set_content_cb (hpdftbl_t t, hpdftbl_content_callback_t cb)
Set table content callback.
Set content callback. This callback gets called for each cell in the table and the returned string will be used as the content. The string will be duplicated so it is safe for a client to reuse the string space. If NULL is returned from the callback then the content will be set to the content specified with the direct content setting. The callback function will receive the Table tag and the row and column
Parameters
t Table handle
cb Callback function
Returns
-1 for error , 0 otherwise
See also
hpdftbl_set_cell_content_cb()
hpdftbl_set_content_style()
int hpdftbl_set_content_style (hpdftbl_t t, char * font, HPDF_REAL fsize, HPDF_RGBColor color, HPDF_RGBColor background)
Set font style for text content.
Set font options for cell content. This will be applied for all cells in the table.
Parameters
t Table handle
font Font name
fsize Font size
color Color
background Background color
Returns
-1 on error, 0 if successful
See also
hpdftbl_set_cell_content_style()
hpdftbl_set_cell_content_style_cb()
hpdftbl_set_content_style_cb()
int hpdftbl_set_content_style_cb (hpdftbl_t t, hpdftbl_content_style_callback_t cb)
Set callback to specify cell content style.
Set callback to format the style for cells in the table. If a cell has its own content style callback that callback will override the generic table callback.
Parameters
t Table handle
cb Callback function
Returns
0 on success, -1 on failure
See also
hpdftbl_set_cell_content_style_cb()
hpdftbl_set_errhandler()
hpdftbl_error_handler_t hpdftbl_set_errhandler (hpdftbl_error_handler_t err_handler)
Specify errhandler for the table routines.
Parameters
err_handler
Returns
The old error handler or NULL if non exists
hpdftbl_set_header_halign()
int hpdftbl_set_header_halign (hpdftbl_t t, hpdftbl_text_align_t align)
Set table header text align.
Set horizontal text alignment for header row
Parameters
t Table handle
align Alignment
Returns
0 on success, -1 on failure
hpdftbl_set_header_style()
int hpdftbl_set_header_style (hpdftbl_t t, char * font, HPDF_REAL fsize, HPDF_RGBColor color, HPDF_RGBColor background)
Specify style for table header row.
Set the font properties and background for the header row which is the top row if enabled. The header row will be automatically enabled after calling this function. The header can be enabled/disabled separately with hpdftbl_use_header()
Parameters
t Table handle
font Font name
fsize Font size
color Font color
background Cell background color
Returns
0 on success, -1 on failure hpdftbl_use_header()
hpdftbl_set_inner_grid_style()
int hpdftbl_set_inner_grid_style (hpdftbl_t t, HPDF_REAL width, HPDF_RGBColor color, hpdftbl_line_dashstyle_t dashstyle)
Set inner border grid style.
Parameters
t Table handle
width Line width (in pt)
color Line color
dashstyle Line dash style
Returns
0 on success, -1 on failure
See also
hpdftbl_set_inner_hgrid_style(), hpdftbl_set_inner_vgrid_style
hpdftbl_set_inner_hgrid_style()
int hpdftbl_set_inner_hgrid_style (hpdftbl_t t, HPDF_REAL width, HPDF_RGBColor color, hpdftbl_line_dashstyle_t dashstyle)
Set inner horizontal border grid style.
Parameters
t Table handle
width Line width (in pt)
color Line color
dashstyle Line dash style
Returns
0 on success, -1 on failure
See also
hpdftbl_set_inner_grid_style()
hpdftbl_set_inner_tgrid_style()
int hpdftbl_set_inner_tgrid_style (hpdftbl_t t, HPDF_REAL width, HPDF_RGBColor color, hpdftbl_line_dashstyle_t dashstyle)
Set inner horizontal top border grid style. This would be the gridline just below the header row.
Parameters
t Table handle
width Line width (in pt)
color Line color
dashstyle Line dash style
Returns
0 on success, -1 on failure
hpdftbl_set_inner_vgrid_style()
int hpdftbl_set_inner_vgrid_style (hpdftbl_t t, HPDF_REAL width, HPDF_RGBColor color, hpdftbl_line_dashstyle_t dashstyle)
Set inner vertical border grid style.
Parameters
t Table handle
width Line width (in pt)
color Line color
dashstyle Line dash style
Returns
0 on success, -1 on failure
See also
hpdftbl_set_inner_grid_style()
hpdftbl_set_label_cb()
int hpdftbl_set_label_cb (hpdftbl_t t, hpdftbl_content_callback_t cb)
Set table label callback.
Set label callback. This callback gets called for each cell in the table and the returned string will be used as the label. The string will be duplicated so it is safe for a client to reuse the string space. If NULL is returned from the callback then the label will be set to the content specified with the direct label setting. The callback function will receive the Table tag and the row and column
Parameters
t Table handle
cb Callback function
Returns
-1 on failure, 0 otherwise
See also
hpdftbl_content_callback_t
hpdftbl_set_cell_label_cb()
hpdftbl_set_label_style()
int hpdftbl_set_label_style (hpdftbl_t t, char * font, HPDF_REAL fsize, HPDF_RGBColor color, HPDF_RGBColor background)
Set the font style for labels.
Set font, color and background options for cell labels.
Parameters
t Table handle
font Font name
fsize Font size
color Color
background Background color
Returns
-1 on error, 0 if successful
hpdftbl_set_labels()
int hpdftbl_set_labels (hpdftbl_t t, char ** labels)
Set the text for the cell labels.
Set labels for all the cell. It is the calling functions responsibility that the labels array is big enough to cover the entire table. The string array corresponds to a flattened 2-d array and the label for cell (r,c) is calculated as (r * num_cols + c) where num_cols is the number of columns in the table. It is allowed to specify NULL as placeholder for empty labels. The actual text in the table will be allocated with strdup() so it is safe to free the memory for the labels after the call to this function. Please note that even if the table contains spanning cells the content data must include empty data for covered cells. For a N x M table the data must have (N*M) entries.
Parameters
t Table handle
labels A one dimensional string array of labels
Returns
-1 on error, 0 if successful
See also
hpdftbl_set_cell_label_cb()
hpdftbl_set_label_cb()
hpdftbl_set_outer_grid_style()
int hpdftbl_set_outer_grid_style (hpdftbl_t t, HPDF_REAL width, HPDF_RGBColor color, hpdftbl_line_dashstyle_t dashstyle)
Set outer border grid style.
Parameters
t Table handle
width Line width (in pt)
color Line color
dashstyle Line dash style
Returns
0 on success, -1 on failure
hpdftbl_set_row_content_style()
int hpdftbl_set_row_content_style (hpdftbl_t t, size_t r, char * font, HPDF_REAL fsize, HPDF_RGBColor color, HPDF_RGBColor background)
Set the font style for an entire row of cells.
Set font options for the specified row of cells. This will override the global cell content .
Parameters
t Table handle
r Row to affect
font Font name
fsize Font size
color Color
background Background color
Returns
0 on success, -1 on failure
See also
hpdftbl_set_content_style()
hpdftbl_set_cell_content_style_cb()
hpdftbl_set_tag()
int hpdftbl_set_tag (hpdftbl_t t, void * tag)
Set an optional tag for the table.
Set an optional tag in the table. The tag can be a pointer to anything. The tag is passed as the first argument in the various callbacks and can be used to supply table specific information or identify a specific table in the case the same callback is used for multiple tables.
Parameters
t The table handle
tag The tag (pointer to any object)
Returns
0 on success, -1 on failure
hpdftbl_set_text_encoding()
void hpdftbl_set_text_encoding (char * target, char * source)
Determine text source encoding.
The default HPDF encoding is a standard PDF encoding. The problem with that is that now almost 100% of all code is written in UTF-8 encoding and trying to print text strings with accented charactes will simply not work. For example the default encoding assumes that strings are given in UTF-8 and sets the target to ISO8859-4 which includes northern europe accented characters. The conversion is internally handled by the standard iconv() routines.
Parameters
target The target encoding. See HPDF documentation for supported encodings.
source The source encodings, i.e. what encodings are sth strings in the source specified in.
hpdftbl_set_title()
int hpdftbl_set_title (hpdftbl_t t, char * title)
Set table title.
Set table title. A title will occupy a separate row above the table that is not included in the row count. A table is enabled when the table text is <> NULL and disabled when the title text is == NULL.
Parameters
t Table handle
title Title string
Returns
0 on success, -1 on failure
See also
hpdftbl_set_title_style()
hpdftbl_set_title_halign()
hpdftbl_set_title_halign()
int hpdftbl_set_title_halign (hpdftbl_t t, hpdftbl_text_align_t align)
Set horizontal alignment for table title.
Set horizontal text alignment for title
Parameters
t Table handle
align Alignment
Returns
0 on success, -1 on failure
See also
hpdftbl_set_title()
hpdftbl_set_title_style()
hpdftbl_set_title_style()
int hpdftbl_set_title_style (hpdftbl_t t, char * font, HPDF_REAL fsize, HPDF_RGBColor color, HPDF_RGBColor background)
Set the table title style.
Set font options for title
Parameters
t Table handle
font Font name
fsize Font size
color Color
background Background color
Returns
0 on success, -1 on failure
See also
hpdftbl_set_title()
hpdftbl_set_title_halign()
hpdftbl_stroke()
int hpdftbl_stroke (HPDF_Doc pdf, const HPDF_Page page, hpdftbl_t t, const HPDF_REAL xpos, const HPDF_REAL ypos, const HPDF_REAL width, HPDF_REAL height)
Stroke the table.
Stroke the table at the specified position and size. The position is by default specified as the upper left corner of the table. Use the hpdftbl_set_origin_top_left(FALSE) to use the bottom left of the table as reference point.
Parameters
pdf The HPDF document handle
page The HPDF page handle
t Table handle
xpos x position for table, bottom left corner
ypos y position for table, bottom left corner
width width of table
height height of table. If the height is specified as 0 it will be automatically calculated. The calculated height can be retrieved after the table has been stroked by a call to hpdftbl_get_last_auto_height()
Returns
-1 on error, 0 if successful
See also
hpdftbl_get_last_auto_height()
hpdftbl_stroke_from_data()
hpdftbl_stroke_from_data()
int hpdftbl_stroke_from_data (HPDF_Doc pdf_doc, HPDF_Page pdf_page, hpdftbl_spec_t * tbl_spec, hpdftbl_theme_t * theme)
Construct the table from a array specification.
Create and stroke a table specified by a data structure. This makes it easier to separate the view of the data from the model which provides the data. The intended use case is that the data structure specifies the core layout of the table together with the labels and callback functions to handle the content in each cell. Using this method to create a table also makes it much more maintainable.
Parameters
pdf_doc The PDF overall document
pdf_page The pageto stroke to
tbl_spec The table specification
theme Table theme to be applied
Returns
0 on success, -1 on failure
See also
hpdftbl_stroke()
hpdftbl_stroke_grid()
void hpdftbl_stroke_grid (HPDF_Doc pdf, HPDF_Page page)
Stroke a point grid on specified page to make it easier to position text and tables.
Parameters
pdf Document handle
page Page handle
Examples
tut_ex01.c, tut_ex02.c, tut_ex02_1.c, tut_ex03.c, tut_ex04.c, tut_ex05.c, tut_ex06.c, tut_ex07.c, tut_ex08.c, tut_ex09.c, tut_ex10.c, tut_ex11.c, tut_ex12.c, tut_ex13_1.c, tut_ex13_2.c, tut_ex14.c, and tut_ex20.c.
hpdftbl_table_widget_letter_buttons()
void hpdftbl_table_widget_letter_buttons (HPDF_Doc doc, HPDF_Page page, HPDF_REAL xpos, HPDF_REAL ypos, HPDF_REAL width, HPDF_REAL height, const HPDF_RGBColor on_color, const HPDF_RGBColor off_color, const HPDF_RGBColor on_background, const HPDF_RGBColor off_background, const HPDF_REAL fsize, const char * letters, _Bool * state)
Display an array of letters as a table where each letter is its own "mini" cell
and sorrounded by a frame. Each boxed letter can be in an "on" state or "off" state which is illustrated with different font and fac colors.
Parameters
doc HPDF document handle
page HPDF page handle
xpos X-osition of cell
ypos Y-Position of cell
width Width of cell
height Height of cell
on_color The font color in "on" state
off_color The font color in "off" state
on_background The face color in "on" state
off_background The face color in "off" state
fsize The font size
letters What letters to have in the boxes
state What state each boxed letter should be (0=off, 1=pn)
Examples
example01.c.
hpdftbl_use_header()
int hpdftbl_use_header (hpdftbl_t t, _Bool use)
Enable/disable the interpretation of the top row as a header row
Parameters
t Table handle
use TRUE to enable, FALSE to disable
Returns
0 on success, -1 on failure
See also
hpdftbl_set_header_style()
hpdftbl_use_labelgrid()
int hpdftbl_use_labelgrid (hpdftbl_t t, _Bool use)
Set the usage of special grid style where the vertical grid only covers the label text and a gap to the next line. Horizontal lines are drawn as usual. The label grid style gives the table a "lighter" look.
Parameters
t Table handle
use TRUE to use label grid, FALSE o disable it
Returns
0 on success, -1 on failure
See also
hpdftbl_use_labels
hpdftbl_use_labels()
int hpdftbl_use_labels (hpdftbl_t t, _Bool use)
Enable/Disable the use of cell labels. By default a newly created table will not use cell labels. Enabling labels will also by default enable the special label grid style. To adjust the grid style separately us the hpdftbl_use_labelgrid() method.
Parameters
t Table handle
use Set to TRUE for cell labels
Returns
0 on success, -1 on failure
See also
hpdftbl_use_labelgrid()
hpdftbl_widget_hbar()
void hpdftbl_widget_hbar (const HPDF_Doc doc, const HPDF_Page page, const HPDF_REAL xpos, const HPDF_REAL ypos, const HPDF_REAL width, const HPDF_REAL height, const HPDF_RGBColor color, const float val, const _Bool hide_val)
Draw a horizontal partially filled bar to indicate an analog (percentage) value.
This function can not be used directly as a canvas callback since it needs additional parameters. Instead create a simple canvas callback that gives the additional parameters.
Parameters
doc HPDF Document handle
page HPDF Page handle
xpos Lower left x
ypos Lower left y
width Width of meter
height Height of meter
color Fill color for bar
val Percentage fill in range [0.0, 100.0]
hide_val TRUE to hide the value (in percent) at the right end of the entire bar
Examples
example01.c.
hpdftbl_widget_segment_hbar()
void hpdftbl_widget_segment_hbar (const HPDF_Doc doc, const HPDF_Page page, const HPDF_REAL xpos, const HPDF_REAL ypos, const HPDF_REAL width, const HPDF_REAL height, const size_t num_segments, const HPDF_RGBColor on_color, const double val_percent, const _Bool hide_val)
Draw a horizontal segment meter that can be used to visualize a discrete value.
This function can not be used directly as a canvas callback since it needs additional parameters. Instead create a simple canvas callback that gives the additional parameters.
Parameters
doc HPDF Document handle
page HPDF Page handle
xpos Lower left x
ypos Lower left y
width Width of meter
height Height of meter
num_segments Total number of segments
on_color Color for "on" segment
val_percent To what extent should the bars be filled (as a value 0.0 - 1.0)
hide_val TRUE to hide the value (in percent) at the right end of the entire bar
Examples
example01.c, and tut_ex14.c.
hpdftbl_widget_slide_button()
void hpdftbl_widget_slide_button (HPDF_Doc doc, HPDF_Page page, HPDF_REAL xpos, HPDF_REAL ypos, HPDF_REAL width, HPDF_REAL height, _Bool state)
Table widget that draws a sliding on/off switch. Meant to be used in a canvas callback to display a boolean value.
This function can not be used directly as a canvas callback since it needs the state of the button as an argument. Instead create a simple canvas callback that determines the wanted state and then just passes on all argument to this widget function.
Parameters
doc HPDF document handle
page HPDF page handle
xpos X-osition of cell
ypos Y-Position of cell
width Width of cell
height Height of cell
state State of button On/Off
Examples
example01.c.
hpdftbl_widget_strength_meter()
void hpdftbl_widget_strength_meter (const HPDF_Doc doc, const HPDF_Page page, const HPDF_REAL xpos, const HPDF_REAL ypos, const HPDF_REAL width, const HPDF_REAL height, const size_t num_segments, const HPDF_RGBColor on_color, const size_t num_on_segments)
Draw a phone strength meter.
This function can not be used directly as a canvas callback since it needs additional parameters. Instead create a simple canvas callback that gives the additional parameters.
Parameters
doc HPDF Document handle
page HPDF Page handle
xpos Lower left x
ypos Lower left y
width Width of meter
height Height of meter
num_segments Total number of segments
on_color Color for "on" segment
num_on_segments Number of on segments
Examples
example01.c, and tut_ex14.c.